<?php

return [
    'username-required' => 'A username or email must be provided.',
    'password-required' => 'Please enter your account password.',
    'email-required' => 'A valid email address must be provided to continue.',

    'login-title' => 'Login to Continue',

    'username-label' => 'Username or Email',
    'password-label' => 'Password',

    'login-button' => 'Login',
    'return' => 'Return to Login',

    'social' => [
        'or' => 'OR',
        'google' => 'Google',
        'discord' => 'Discord',
        'github' => 'GitHub',
        'not_linked' => 'This account has not been linked to any :provider account. Please log in with your email and password first, then link your :provider account in the Account Settings page.',
    ],

    'forgot-password' => [
        'title' => 'Request Password Reset',
        'label' => 'Forgot Password?',
        'email-label' => 'Email',
        'email-content' => 'Enter your account email address to receive instructions on resetting your password.',
        'send-email' => 'Send Email',
    ],

    'checkpoint' => [
        'title' => 'Device Checkpoint',
        'recovery-code' => 'Recovery Code',
        'auth-code' => 'Authentication Code',
        'is-missing' => 'Enter one of the recovery codes generated when you setup 2-Factor authentication on this account in order to continue.',
        'is-not-missing' => 'Enter the two-factor token generated by your device.',
        'button' => 'Continue',
        'lost-device' => 'I\'ve Lost My Device',
        'not-lost-device' => 'I Have My Device',

    ],

    'reset-password' => [
        'new-required' => 'A new password is required.',
        'min-required' => 'Your new password should be at least 8 characters in length.',
        'no-match' => 'Your new password does not match.',
        'email-label' => 'Email',
        'new-label' => 'New Password',
        'min-length' => 'Passwords must be at least 8 characters in length.',
        'confirm-label' => 'Confirm New Password',
        'label' => 'Reset Password',
    ],

    'register' => [
        'no-match' => 'Your password does not match.',
        'namefirst-label' => 'First Name',
        'namelast-label' => 'Last Name',
        'email-label' => 'Email',
        'username-label' => 'UserName',
        'password-label' => 'Password',
        'min-length' => 'Passwords must be at least 8 characters in length.',
        'confirm-label' => 'Confirm Password',
        'label' => 'Register',
    ],
    
    'failed' => 'No account matching those credentials could be found.',

    'two_factor' => [
        'label' => '2-Factor Token',
        'label_help' => 'This account requires a second layer of authentication in order to continue. Please enter the code generated by your device to complete this login.',
        'checkpoint_failed' => 'The two-factor authentication token was invalid.',
    ],

    'throttle' => 'Too many login attempts. Please try again in :seconds seconds.',
    'password_requirements' => 'Password must be at least 8 characters in length and should be unique to this site.',
    '2fa_must_be_enabled' => 'The administrator has required that 2-Factor Authentication be enabled for your account in order to use the Panel.',
];
